### ISSUE TITLE
H2 header is not closed

### ISSUE THREAD

**Issue by ssbunyk** [tatarintseva/tatarintseva.github.io#2] opened 2015-01-19 14:15 UTC

**Comment by tatarintseva** [comment] 2015-01-19 14:28
Thanks. The issue is resolved in commit "header h2 closed"

**Comment by byshovets** [comment] 2015-01-19 14:44
Should be fa0b916da500ff6e7f16aa31330be647ee6a374a, not "header h2 closed"

**Comment by tatarintseva** [comment] 2015-01-19 14:49
OK, will take into account for future commits

**Closed as completed** 2015-01-19 14:59 UTC
